let jokes = [
  "I've decided to sell my Hoover... well it was just collecting dust.",
  "I've written a joke about a fat badger but I couldn't fit it into my set.",
  "Always leave them wanting more my uncle used to say to me. Which is why he lost his job in disaster relief.",
  "I was given some Sudoku toilet paper. It didn't work. You could only fill it in with number ones and number twos.",
  "I wanted to do a show about feminism. But my husband wouldn't let me.",
  "Money can't buy you happiness? Well check this out I bought myself a Happy Meal.",
  "Scotland had oil but it's running out thanks to all that deep frying.",
  "I've been married for 10 years I haven't made a decision for seven.",
  "This show is about perception and perspective. But it depends how you look at it.",
  "I've written a joke about a fat badger but I couldn't fit it into my set.",
  "I heard a rumour that Cadbury is bringing out an oriental chocolate bar. Could be a Chinese Wispa.",
  "I used to work in a shoe-recycling shop. It was sole-destroying.",
  "I'm in a same-sex marriage... the sex is always the same.",
  "My friend told me he was going to a fancy dress party as an Italian island. I said to him 'Don't be Sicily'.",
  "I can give you the cause of anaphylactic shock in a nutshell.",
  "The Pope is a lot like Doctor Who. He never dies just keeps being replaced by white men.",
  "You know you are fat when you hug a child and it gets lost.",
  "The universe implodes. No matter.",
  "I was adopted at birth and have never met my mum. That makes it very difficult to enjoy any lapdance.",
  "The good thing about lending someone your time machine is that you basically get it back immediately.",
  "You know who really gives kids a bad name? Posh and Becks.",
  "Last night me and my girlfriend watched three DVDs back to back. Luckily I was the one facing the telly.",
  "I was raised as an only child which really annoyed my sister.",
  "You know you're working class when your TV is bigger than your book case.",
  "I'm good friends with 25 letters of the alphabet... I don't know Y.",
  "I took part in the sun tanning Olympics - I just got Bronze.",
  "Pornography is often frowned upon but that's only because I'm concentrating.",
  "I saw a documentary on how ships are kept together. Riveting!",
  "I waited an hour for my starter so I complained: 'It's not rocket salad.",
  "My mum's so pessimistic that if there was an Olympics for pessimism... she wouldn't fancy her chances.",
  "I needed a password eight characters long so I picked Snow White and the Seven Dwarves.",
  "Crime in multi-storey car parks. That is wrong on so many different levels.",
  "People say 'I'm taking it one day at a time'. You know what? So is everybody. That's how time works.",
  "Drive-Thru McDonalds was more expensive than I thought... once you've hired the car...",
  "I was playing chess with my friend and he said 'Let's make this interesting'. So we stopped playing chess.",
  "My mother told me you don't have to put anything in your mouth you don't want to. Then she made me eat broccoli which felt like double standards.",
  "I was in a band which we called The Prevention because we hoped people would say we were better than The Cure.",
  "Someone asked me recently - what would I rather give up food or sex. Neither! I'm not falling for that one again wife.",
  "I admire these phone hackers. I think they have a lot of patience. I can't even be bothered to check my OWN voicemails.",
  "My friend died doing what he loved ... Heroin.",
  "I've just been on a once-in-a-lifetime holiday. I'll tell you what never again.",
  "I'm currently dating a couple of anorexics. Two birds one stone.",
  "I picked up a hitch hiker. You've got to when you hit them.",
  "I bought one of those anti-bullying wristbands when they first came out. I say 'bought' I actually stole it off a short fat ginger kid.",
  "As a kid I was made to walk the plank. We couldn't afford a dog.",
  "Being an England supporter is like being the over-optimistic parents of the fat kid on sports day.",
  "What do you call a kid with no arms and an eyepatch? Names.",
  "Dave drowned. So at the funeral we got him a wreath in the shape of a lifebelt. Well it's what he would have wanted.",
  "For Vanessa Feltz life is like a box of chocolates: Empty.",
  "Wooden spoons are great. You can either use them to prepare food. Or if you can't be bothered with that just write a number on one and walk into a pub...",
  "Hedgehogs - why can't they just share the hedge?",
  "I was watching the London Marathon and saw one runner dressed as a chicken and another runner dressed as an egg. I thought: 'This could be interesting'.",
  "I had my boobs measured and bought a new bra. Now I call them Joe Cocker and Jennifer Warnes because they're up where they belong.",
  "I went on a girls' night out recently. The invitation said 'dress to kill'. I went as Rose West.",
  "I'm sure wherever my dad is; he's looking down on us. He's not dead just very condescending.",
  "Going to Starbucks for coffee is like going to prison for sex. You know you're going to get it but it's going to be rough.",
  "To the people who've got iPhones: you just bought one you didn't invent it!",
  "A spa hotel? It's like a normal hotel only in reception there's a picture of a pebble.",
  "I've been reading the news about there being a civil war in Madagascar. Well I've seen it six times and there isn't.",
  "I started so many fights at my school - I had that attention-deficit disorder. So I didn't finish a lot of them"
]

function getRandomJoke() {
  let rand = Math.floor(Math.random() * Math.floor(jokes.length - 1))
  console.log(rand);

  return jokes[2]
}

module.exports = jokes